#!groovy

// Generated by IBM TransformationAdvisor
// Tue Apr 16 15:55:16 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}